using System;
using System.Collections.Generic;
using System.Globalization;

namespace Jellyfin.Plugin.WhisperSubtitles.Output;

/// <summary>
/// The three facts about how one subtitle was produced: this plugin, the backend
/// that ran, and the model it ran.
/// </summary>
/// <remarks>
/// The same three facts go in two places for two readers. The file name carries a
/// marker a viewer sees in a track list, which is <see cref="GeneratedSubtitleName"/>
/// and says only that a machine wrote it. This is the other reader: an operator
/// who opens the file, or who reads the plugin's own record for the item, and who
/// is asking which backend and which model, because that is what decides whether
/// a bad transcription is worth running again with something larger.
///
/// The values are recorded rather than configured. What belongs here is what
/// actually ran, so a subtitle written before a model was changed still says
/// which model wrote it.
/// </remarks>
public sealed class SubtitleProvenance
{
    /// <summary>
    /// What the header lines start with.
    /// </summary>
    /// <remarks>
    /// SubRip has no comment syntax to use, so this is a convention rather than
    /// part of the format. A semicolon and a space is the least ambiguous prefix
    /// available: it is not a digit, so no line here can be read as a cue index,
    /// and it holds no arrow, so no line here can be read as a timing.
    /// </remarks>
    public const string HeaderPrefix = "; ";

    /// <summary>
    /// Initializes a new instance of the <see cref="SubtitleProvenance"/> class.
    /// </summary>
    /// <param name="backend">The backend that produced the segments.</param>
    /// <param name="model">The model it used.</param>
    public SubtitleProvenance(string backend, string model)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(backend);
        ArgumentException.ThrowIfNullOrWhiteSpace(model);

        Backend = backend;
        Model = model;
    }

    /// <summary>
    /// Gets the name this plugin gives itself in a file it wrote.
    /// </summary>
    public static string Plugin => "Whisper Subtitles";

    /// <summary>
    /// Gets the backend that produced the segments.
    /// </summary>
    public string Backend { get; }

    /// <summary>
    /// Gets the model the backend used.
    /// </summary>
    public string Model { get; }

    /// <summary>
    /// The lines that go at the top of the file, without their line endings.
    /// </summary>
    /// <returns>One line per fact, in a fixed order.</returns>
    /// <remarks>
    /// A line per fact rather than one line holding all three, so a reader
    /// looking for the model does not have to parse a sentence, and so a value
    /// carrying the separator of a one-line form cannot make the line say
    /// something else. Any line ending in a value is replaced with a space for
    /// the same reason: a value arriving from a backend's own output must not be
    /// able to add a line to this block.
    /// </remarks>
    public IReadOnlyList<string> HeaderLines() =>
    [
        Line("Generated by", Plugin),
        Line("Backend", Backend),
        Line("Model", Model)
    ];

    private static string Line(string label, string value) =>
        string.Create(
            CultureInfo.InvariantCulture,
            $"{HeaderPrefix}{label}: {OneLine(value)}");

    private static string OneLine(string value) =>
        value.Replace("\r\n", " ", StringComparison.Ordinal)
            .Replace('\r', ' ')
            .Replace('\n', ' ');
}
