name: '📝 Create/Update Release Draft & Release Bump PR'

on:
  push:
    branches:
      - master
    paths-ignore:
      - build.yaml
  workflow_dispatch:
  repository_dispatch:
    types:
      - update-prep-command

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/changelog.yaml@eb99033a7ff644881b014bc0b4169916c854a68b # master, 2026-07-29
    with:
      repository-name: jellyfin/jellyfin-plugin-template
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
